"use client";

import React, { useState } from "react";
import { useRouter } from "next/navigation";
import Header from "@/components/luxcomp/header";
import Footer from "@/components/luxcomp/footer";
import { toast } from "sonner";
import { Loader2Icon, ShieldAlertIcon, KeyIcon } from "lucide-react";
import { apiClient, fetchCsrfToken } from "@/lib/api";

export default function TwoFactorPage() {
  const router = useRouter();
  const [code, setCode] = useState("");
  const [useRecoveryCode, setUseRecoveryCode] = useState(false);
  const [recoveryCode, setRecoveryCode] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!useRecoveryCode && (!code || code.length < 6)) {
      toast.error("Please enter a valid 6-digit authentication code");
      return;
    }

    if (useRecoveryCode && !recoveryCode.trim()) {
      toast.error("Please enter an emergency recovery code");
      return;
    }

    setLoading(true);
    try {
      await fetchCsrfToken();
      const payload = useRecoveryCode
        ? { recovery_code: recoveryCode.trim() }
        : { code: code.trim() };

      const res = await apiClient.post("/two-factor-challenge", payload);
      toast.success("Identity verified successfully!");

      const user = res.data?.user;
      const isAdmin =
        user?.roles &&
        Array.isArray(user.roles) &&
        user.roles.some((r: string | { name?: string }) =>
          typeof r === "string" ? r.toLowerCase() === "admin" : r.name?.toLowerCase() === "admin"
        );

      if (isAdmin) {
        router.push("/dashboard");
      } else {
        router.push("/profile");
      }
      router.refresh();
    } catch (error) {
      const err = error as { response?: { data?: { message?: string } } };
      const msg = err.response?.data?.message || "Invalid authentication or recovery code";
      toast.error(msg);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex min-h-screen flex-col bg-white">
      <Header />
      <main className="flex flex-1 items-center justify-center px-4 py-16">
        <div className="w-full max-w-md flex flex-col items-center space-y-6">
          <div className="text-center space-y-2">
            <div className="size-12 rounded-full bg-slate-100 text-slate-900 flex items-center justify-center mx-auto mb-2">
              <ShieldAlertIcon className="size-6" />
            </div>
            <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">
              Two-Factor Authentication
            </h1>
            <p className="text-xs text-slate-600 max-w-xs mx-auto leading-relaxed">
              {useRecoveryCode
                ? "Enter one of your emergency recovery codes to access your account"
                : "Enter the 6-digit authentication passcode generated by your device"}
            </p>
          </div>

          <div className="w-full max-w-sm rounded-3xl border border-gray-300/80 bg-white p-7 shadow-xs">
            <form onSubmit={handleSubmit} className="space-y-4">
              {!useRecoveryCode ? (
                <div className="space-y-1.5">
                  <label
                    htmlFor="2fa-code"
                    className="text-xs font-semibold text-slate-800"
                  >
                    6-Digit Passcode:
                  </label>
                  <input
                    id="2fa-code"
                    placeholder="123456"
                    maxLength={6}
                    value={code}
                    onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
                    className="w-full h-11 px-3 rounded-lg bg-[#ECECEC] text-sm text-slate-900 font-mono text-center tracking-[0.3em] font-bold border-0 focus:outline-hidden focus:ring-1 focus:ring-slate-400 transition-all"
                    autoFocus
                    required
                  />
                </div>
              ) : (
                <div className="space-y-1.5">
                  <label
                    htmlFor="recovery-code"
                    className="text-xs font-semibold text-slate-800"
                  >
                    Emergency Recovery Code:
                  </label>
                  <input
                    id="recovery-code"
                    placeholder="xxxx-xxxx-xxxx"
                    value={recoveryCode}
                    onChange={(e) => setRecoveryCode(e.target.value)}
                    className="w-full h-11 px-3 rounded-lg bg-[#ECECEC] text-xs text-slate-900 font-mono text-center border-0 focus:outline-hidden focus:ring-1 focus:ring-slate-400 transition-all"
                    autoFocus
                    required
                  />
                </div>
              )}

              <div className="pt-2">
                <button
                  type="submit"
                  disabled={loading}
                  className="w-full h-11 rounded-lg bg-slate-900 hover:bg-black text-white text-xs font-semibold flex items-center justify-center transition-colors shadow-xs cursor-pointer"
                >
                  {loading ? (
                    <Loader2Icon className="size-4 animate-spin" />
                  ) : (
                    "Verify & Continue"
                  )}
                </button>
              </div>

              <div className="pt-2 text-center">
                <button
                  type="button"
                  onClick={() => {
                    setUseRecoveryCode(!useRecoveryCode);
                    setCode("");
                    setRecoveryCode("");
                  }}
                  className="text-xs font-semibold text-[#7A1C24] hover:underline inline-flex items-center gap-1"
                >
                  <KeyIcon className="size-3" />
                  {useRecoveryCode
                    ? "Use Authenticator App Code"
                    : "Use Emergency Recovery Code"}
                </button>
              </div>
            </form>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}